---
- name: add php 7.1 repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: install php and modules
  apt:
    pkg: "{{ item  }}"
    state: present
  with_items:
    - php7.1
    - php7.1-fpm
    - php7.1-curl
    - php7.1-cli
    - php7.1-xml
    - php7.1-intl
    - php7.1-zip
    - php7.1-mbstring
    - php7.1-gd
    - acl
